Could save some time by not computing reflection of mirror points since they don't move.

In [2]:
using NBInclude, Winston
nbinclude("Reptile Tools V2.ipynb")

pianglecheck (generic function with 2 methods)

In [2]:
function reflect(mirror, point)
    #reflects `point` over `mirror`. 'point` = [x1 y1; x2 y2; ...]. `mirror` = [x1 y1; x2 y2].
    
    if mirror[2,1] - mirror[1,1] != 0 #slope exists
        slope = (mirror[2,2] - mirror[1,2])/(mirror[2,1] - mirror[1,1]) #mirror's slope
        x = (slope^2*mirror[1,1]+(point[:,2].-mirror[1,2])*slope+point[:,1])/(slope^2+1) #intersection of mirror and line through point
        x = 2 * x - point[:,1] #reflected x-coordinate
        if slope != 0 #not horizontal
            y = -1/slope*(x - point[:,1])+point[:,2]
        else #slope horizontal
            y = -point[:,2] .+ 2 * mirror[1,2]
        end
    else #infinite slope
        x = -point[:,1] .+ 2 * mirror[1,1]
        y = point[:,2]
    end
    
    return [x y]
end

reflect (generic function with 1 method)

In [3]:
function reflecttile(tile, side::Int)
    #reflects `tile` over the side given by `side'. 'tile' = [x1 y1; x2 y2; ...]
    #returns new tile in proper order with reflected side (and verticies on a side) deleted
    
    #reflect
    if side < size(tile)[1] #not last side
        mirror = tile[side:side+1,:]
    elseif side == size(tile)[1] #last side
        mirror = [tile[end,:]; tile[1,:]]      
    else #error
        error("side exceeds the number of tile sides")
    end
    
    newtile = reflect(mirror, tile) #combination of original and new, reflected points
    
    #combine original and reflection
    if side < size(tile)[1] #not last side
        newtile = [tile[1:side,:]; flipdim(newtile[side+2:end,:],1); 
                flipdim(newtile[1:side-1,:],1); tile[side+1:end,:]]
    else
        newtile = [tile[1:side,:]; flipdim(newtile[2:side-1,:],1)]
    end
    
    #check for points lieing on a side (i.e. 180 degree angles)
    newtile = pianglecheck(newtile)
    
    newtile = reshape(ordertiles(reshape(newtile,(size(newtile)[1],2,1))), (size(newtile)[1],2)) #ordertiles expect a 3d matrix
    
    return newtile
end
        

reflecttile (generic function with 1 method)

In [51]:
function reflectcheck(db, reptile, digits = 9)
    #attempts to create a reflective child of `reptile` and saves it in `db`
    
    
    ###########start over##########
    #need to work with pairs of verticies (edges) forward and reverse
    
    for i = 1:reptile[1,:n]#loop through each side
        
        verticies = round(reptile[1, :tiles][:,:,i], digits) #all of the ith verticies
        edges = [verticies circshift(verticies, -1)] #each row is an edge [x1 y1 x2 y2]
        
        #check if 
        
        #check if mirrored tile edges align
        for j = 1:reptile[1, :m] #loop through each tile
            
            #forward direction
            temp = edges[j,:] .== [edges[1:j-1,:]; edges[j+1:end,:]] #points that match x1, y1, x2, y2
            matchededges = temp[:,1] & temp[:,2] & temp[:,3] & temp[:,4] #matching edges
        end
    end
    

    
    
    
    
    
    for i = 1:reptile[1,:n]#loop through each side
        
        verticies = round(reptile[1, :tile][:,:,i], digits) #all of the ith verticies
        
        for j = 1:reptile[1, :m] #loop through each tile
            
            
            
            #check if mirrored tile edges align
            temp = verticies[j,:] .== [vertices[1:j-1,:]; verticies[j+1:end,:]]
            matchedverticies = temp[:,1] & temp[:,2] #points that match x and y
            vals, lens = rle(matchedverticies) #run values and lengths
            if max(lens) > 2 
            
            #check if mirrored tile edge is on mirrored original edge
            original = reptile[1, :points] #original's verticies
            originalslope = 1
            end
        end
    end
   
end

reflectcheck (generic function with 2 methods)

In [52]:
reflectcheck(reptiles, getrep(reptiles, (4,4,1)))

4x4 Array{Float64,2}:
 0.0  0.0  0.0  1.0
 0.0  1.0  0.5  1.0
 0.5  1.0  0.5  0.5
 0.5  0.5  0.0  0.0

In [47]:
?findtiles

search: findtiles



No documentation found.

`findtiles` is a generic `Function`.

```julia
# 1 method for generic function "findtiles":
findtiles(points, rotate, reflect, translate) at C:\Users\Nun Maker\Dropbox\Jupyter\Fractals\Shape Fractals\Reptile Tools V2.ipynb:In[388]:5
```


In [34]:
sort([1 3; 35 3; 32 4;2 5; 2 6],1)

5x2 Array{Int64,2}:
  1  3
  2  3
  2  4
 32  5
 35  6

In [15]:
map(x->x == [3 4],[3 4; 3 6; 5 34])

3x2 Array{Bool,2}:
 false  false
 false  false
 false  false

In [5]:
map()

3x2 Array{Int64,2}:
 3   4
 5   6
 5  34

In [13]:
?map

search: map map! mapfoldr mapfoldl mapslices mapreduce mapreducedim pmap Mmap



```
map(f, c...) -> collection
```

Transform collection `c` by applying `f` to each element. For multiple collection arguments, apply `f` elementwise.

```jldoctest
julia> map((x) -> x * 2, [1, 2, 3])
3-element Array{Int64,1}:
 2
 4
 6

julia> map(+, [1, 2, 3], [10, 20, 30])
3-element Array{Int64,1}:
 11
 22
 33
```


In [105]:
testrep = getrep(reptiles, (4,4,1))[1,:tiles]

4x2x4 Array{Float64,3}:
[:, :, 1] =
 1.22465e-16  0.0
 0.0          1.0
 0.5          1.0
 0.5          0.5

[:, :, 2] =
 0.0  6.12323e-17
 0.5  0.5        
 1.0  0.5        
 1.0  0.0        

[:, :, 3] =
 0.0  1.0
 0.0  2.0
 0.5  1.5
 0.5  1.0

[:, :, 4] =
 0.5  0.5
 0.5  1.5
 1.0  1.0
 1.0  0.5

In [110]:
reflecttile(testrep[:,:,2],2)

5x2 Array{Float64,2}:
 0.0  1.0        
 1.0  0.5        
 1.0  0.0        
 0.0  6.12323e-17
 1.0  1.0        